nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    allow_credentials: true  # Autorise l'envoi des cookies/credentiels
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    #    allow_headers: ['*']
    #    expose_headers: [ '*' ]
    allow_headers: [ 'Content-Type', 'Authorization' ]
    expose_headers: [ 'Authorization' ]
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_credentials: true  # Autorise l'envoi des cookies/credentiels
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE','OPTIONS' ]
      max_age: 3600
    '^/api/login_check':
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE','OPTIONS' ]
      max_age: 3600
